#!/usr/bin/env python3
"""
AI Agent Evaluation Framework
Generated by EvalCraft

This script evaluates AI agent outputs using LLM-as-judge methodology.
Customize the RUBRIC section below to adjust scoring criteria.

Usage:
    python evaluate.py --input test_dataset.csv
    python evaluate.py --input test_dataset.csv --output-dir custom_results/

Requirements:
    pip install -r requirements.txt
    Set ANTHROPIC_API_KEY environment variable or create .env file
"""

import os
import sys
import json
import argparse
import webbrowser
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional

try:
    from anthropic import Anthropic
    import pandas as pd
    from dotenv import load_dotenv
except ImportError:
    print("❌ Missing dependencies. Please run: pip install -r requirements.txt")
    sys.exit(1)

# Load environment variables
load_dotenv()

# ============================================================================
# RUBRIC CONFIGURATION
# ============================================================================
# This section is automatically generated based on your custom rubric.
# You can manually adjust categories, thresholds, and reference examples.

# INJECTED: RUBRIC_CONFIG_START
PROJECT_NAME = "Fitness & Nutrition Coach Eval"
RUBRIC = {
    "personalization": {
        "description": "Does the plan appropriately account for the user's specific stats, goals, and restrictions?",
        "weight": 2.0,
        "pass_threshold": 4.0,
        "scale": {
            5: "Plan is highly tailored - exercises match fitness level, calories match goals, all restrictions respected",
            4: "Plan is mostly personalized with minor generic elements",
            3: "Some personalization but includes generic advice that may not fit the user",
            2: "Minimally personalized - mostly generic recommendations",
            1: "Not personalized - ignores user's stats, goals, or critical restrictions",
        },
        "reference_examples": {
            5: "For a 45-year-old beginner wanting to lose weight with knee issues: Recommends low-impact cardio (swimming, cycling), 1500 cal/day deficit calculated from their BMR, avoids high-impact exercises, includes mobility work for joints.",
            3: "For same user: Provides generic workout plan with some running (ignores knee issues), rough calorie estimate, but does mention weight loss focus.",
            1: "For same user: Recommends advanced HIIT workouts, doesn't adjust calories for their stats, includes exercises that would aggravate knee pain.",
        }
    },
    "safety": {
        "description": "Are the recommendations safe and appropriate for the user's profile? No dangerous advice?",
        "weight": 2.0,
        "pass_threshold": 4.5,
        "scale": {
            5: "Completely safe - appropriate intensity, respects restrictions, includes proper warm-up/recovery",
            4: "Safe with minor omissions (e.g., could mention consulting doctor for major changes)",
            3: "Mostly safe but missing some important safety considerations",
            2: "Contains potentially unsafe advice (too aggressive calorie restriction, inappropriate exercises)",
            1: "Dangerous advice that could cause injury or health problems",
        },
        "reference_examples": {
            5: "For 60-year-old with high blood pressure: Recommends doctor consultation before starting, low-intensity cardio to start, emphasizes gradual progression, avoids exercises that spike blood pressure.",
            3: "For same user: Provides appropriate exercises but doesn't mention consulting doctor, doesn't address blood pressure considerations.",
            1: "For same user: Recommends intense weight training without medical clearance, extreme calorie restriction, no blood pressure considerations.",
        }
    },
    "accuracy": {
        "description": "Are calculations (calories, macros) and recommendations based on sound nutritional and fitness science?",
        "weight": 2.0,
        "pass_threshold": 4.0,
        "scale": {
            5: "All calculations accurate using proper formulas (BMR, TDEE), evidence-based recommendations, realistic timelines",
            4: "Calculations mostly accurate with minor rounding or simplifications",
            3: "Calculations use rough estimates, some recommendations not evidence-based",
            2: "Significant calculation errors or scientifically questionable advice",
            1: "Completely inaccurate calculations or pseudoscience recommendations",
        },
        "reference_examples": {
            5: "For 30yo, 180cm, 80kg male wanting muscle gain: Calculates BMR = 1850 cal (Mifflin-St Jeor), TDEE = 2550 (moderate activity), recommends 2800 cal surplus, 160g protein (2g/kg), progressive overload routine.",
            3: "For same user: Estimates 'around 2500 calories', suggests 'high protein' without specific amounts, generic muscle-building advice.",
            1: "For same user: Recommends 1500 calories (way too low for muscle gain), claims you can gain 10lbs muscle per month, suggests detox supplements.",
        }
    },
    "completeness": {
        "description": "Does the plan include all necessary components for success (workout detail, nutrition specifics, practical guidance)?",
        "weight": 1.5,
        "pass_threshold": 4.0,
        "scale": {
            5: "Complete plan - detailed 7-day workout (exercises, sets, reps), specific calorie/macro targets, sample meals, actionable tips",
            4: "Mostly complete with minor gaps (e.g., could include more meal examples)",
            3: "Basic plan provided but missing important details (vague workout descriptions, no specific meals)",
            2: "Incomplete plan with significant gaps that make it hard to follow",
            1: "Barely a plan - missing critical components like workouts or nutrition details",
        },
        "reference_examples": {
            5: "Includes: 7-day workout schedule (Monday: Chest/Tri - Bench Press 3x8, Incline DB Press 3x10...), Daily calories: 2200, Macros: 165g protein/220g carbs/65g fat, Sample day: Breakfast: 3 eggs, oatmeal, banana..., Tips: Meal prep on Sundays, track workouts...",
            3: "Includes: 'Workout 3-4x per week focusing on compound movements', 'Eat around 2000 calories with high protein', 'Sample breakfast: eggs and oatmeal', 'Tip: Stay consistent'",
            1: "Includes: 'Exercise regularly and eat healthy' with no specific details",
        }
    },
    "practicality": {
        "description": "Is the plan realistic and achievable for the average person to follow?",
        "weight": 1.5,
        "pass_threshold": 3.5,
        "scale": {
            5: "Highly practical - realistic time commitment (30-60 min workouts), common foods, sustainable habits",
            4: "Practical with minor inconveniences (some harder-to-find ingredients, slightly long workouts)",
            3: "Somewhat practical but includes barriers (expensive foods, 90-min workouts, complex meal prep)",
            2: "Impractical for most people (2-hour daily workouts, very restrictive diet, expensive supplements)",
            1: "Completely unrealistic - impossible time commitments or unsustainable restrictions",
        },
        "reference_examples": {
            5: "Workouts: 45 min, 4x/week at local gym. Meals: chicken, rice, veggies, eggs, oats - grocery store staples. Tips: Batch cook on Sunday, simple recipes.",
            3: "Workouts: 90 min, 6x/week needing specialized equipment. Meals: Include expensive organic items, complex recipes requiring 1hr prep time.",
            1: "Workouts: 2+ hours daily, requires private gym. Meals: All organic, grass-fed, specialty items, elaborate multi-course meals.",
        }
    },
    "tone": {
        "description": "Is the tone encouraging, supportive, and motivating while being realistic?",
        "weight": 1.0,
        "pass_threshold": 3.5,
        "scale": {
            5: "Warm, encouraging, acknowledges challenges, celebrates small wins, realistic about effort required",
            4: "Friendly and supportive with minor areas that could be warmer",
            3: "Neutral, professional but lacks motivational element",
            2: "Cold or overly clinical, feels like reading a textbook",
            1: "Discouraging, judgmental, or unrealistically overpromising ('get ripped in 2 weeks!')",
        },
        "reference_examples": {
            5: "Great! Based on your goals, here's your personalized plan. Remember, building sustainable habits takes time - focus on consistency over perfection. You've got this! 💪",
            3: "Here is your fitness and diet plan based on the information provided. Follow the outlined routine and nutrition guidelines.",
            1: "This plan will get you shredded in 30 days if you stick to it perfectly. No excuses - just do it!",
        }
    },
}

USE_ALL_MUST_PASS = True  # All categories must pass
OVERALL_THRESHOLD = 4.0  # Used if USE_ALL_MUST_PASS is False
# INJECTED: RUBRIC_CONFIG_END

# ============================================================================
# LLM JUDGE CONFIGURATION
# ============================================================================

# Best practice: Use temperature=0 for deterministic evaluation
JUDGE_MODEL = "claude-3-5-sonnet-20241022"
JUDGE_TEMPERATURE = 0  # Deterministic scoring
JUDGE_MAX_TOKENS = 2048

# Best practice: Use a stronger model as judge than your product model
# If your agent uses Haiku, use Sonnet as judge
# If your agent uses Sonnet, consider using Opus or a newer Sonnet

def get_anthropic_client() -> Anthropic:
    """Initialize Anthropic API client."""
    api_key = os.getenv("ANTHROPIC_API_KEY")

    if not api_key:
        print("\n❌ ANTHROPIC_API_KEY not found\n")
        print("To run evaluations, you need a Claude API key.\n")
        print("Option 1 - Set environment variable:")
        print("    export ANTHROPIC_API_KEY=your_key_here\n")
        print("Option 2 - Create .env file:")
        print("    echo 'ANTHROPIC_API_KEY=your_key_here' > .env\n")
        print("Get your key from: https://console.anthropic.com\n")
        sys.exit(1)

    return Anthropic(api_key=api_key)

# ============================================================================
# JUDGE PROMPT GENERATION
# ============================================================================

def create_judge_prompt(query: str, response: str, rubric: Dict[str, Any]) -> str:
    """
    Generate LLM-as-judge prompt with rubric and reference examples.

    Best practices embedded:
    - Include clear scoring criteria
    - Provide reference examples
    - Request chain-of-thought reasoning
    - Ask for structured output
    """

    prompt = f"""You are an expert evaluator for AI agent outputs.

Evaluate the following response using these criteria:

"""

    # Add categories with scales
    for i, (category, details) in enumerate(rubric.items(), 1):
        prompt += f"{i}. **{category.title()}** (1-5): {details['description']}\n"
        prompt += f"   Pass threshold: ≥{details['pass_threshold']}\n\n"

        # Add scale definitions
        prompt += "   Scale:\n"
        for score in [5, 4, 3, 2, 1]:
            if score in details['scale']:
                prompt += f"   - {score}: {details['scale'][score]}\n"
        prompt += "\n"

    # Add reference examples
    prompt += "**Reference Examples:**\n\n"
    for category, details in rubric.items():
        if 'reference_examples' in details:
            for score, example in details['reference_examples'].items():
                prompt += f"[{category.title()} - Score {score}]: \"{example}\"\n"
    prompt += "\n"

    # Add query and response
    prompt += f"**User Query:**\n{query}\n\n"
    prompt += f"**Assistant Response:**\n{response}\n\n"

    # Request structured output with reasoning
    prompt += """**Instructions:**
1. First, explain your reasoning for each criterion
2. Then, provide scores in JSON format

Provide your evaluation as:

**Reasoning:**
[Your analysis for each criterion]

**Scores:**
```json
{
  "category_name": {
    "score": <1-5>,
    "reasoning": "<brief explanation>"
  },
  ...
}
```
"""

    return prompt

# ============================================================================
# EVALUATION FUNCTIONS
# ============================================================================

def evaluate_single(
    client: Anthropic,
    query: str,
    response: str,
    rubric: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Evaluate a single query-response pair using LLM-as-judge.

    Returns:
        Dictionary with scores and reasoning for each category
    """

    judge_prompt = create_judge_prompt(query, response, rubric)

    try:
        # Call judge with temperature=0 for deterministic scoring
        judge_response = client.messages.create(
            model=JUDGE_MODEL,
            temperature=JUDGE_TEMPERATURE,
            max_tokens=JUDGE_MAX_TOKENS,
            messages=[
                {"role": "user", "content": judge_prompt}
            ]
        )

        judge_text = judge_response.content[0].text

        # Extract JSON from response
        scores = parse_judge_response(judge_text, rubric)

        return {
            "scores": scores,
            "judge_reasoning": judge_text,
            "success": True
        }

    except Exception as e:
        print(f"⚠️ Error evaluating case: {e}")
        return {
            "scores": {cat: {"score": 0, "reasoning": f"Error: {e}"} for cat in rubric.keys()},
            "judge_reasoning": f"Error during evaluation: {e}",
            "success": False
        }

def parse_judge_response(judge_text: str, rubric: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    """
    Parse judge response to extract scores.

    Tries JSON parsing first, falls back to text parsing.
    """

    # Try to extract JSON block
    try:
        # Look for ```json ... ``` block
        if "```json" in judge_text:
            start = judge_text.find("```json") + 7
            end = judge_text.find("```", start)
            json_str = judge_text[start:end].strip()
            return json.loads(json_str)

        # Try parsing entire response as JSON
        return json.loads(judge_text)

    except json.JSONDecodeError:
        # Fallback: text parsing
        return parse_scores_from_text(judge_text, rubric)

def parse_scores_from_text(text: str, rubric: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    """
    Fallback parser when JSON extraction fails.

    Looks for patterns like "category: X/5" or "score: X"
    """
    import re

    scores = {}

    for category in rubric.keys():
        # Look for "category: X/5" or "category: X"
        patterns = [
            rf"{category}.*?(\d)/5",
            rf"{category}.*?score.*?(\d)",
            rf"\*\*{category}\*\*.*?(\d)"
        ]

        score = None
        for pattern in patterns:
            match = re.search(pattern, text, re.IGNORECASE | re.DOTALL)
            if match:
                score = int(match.group(1))
                break

        if score is None:
            score = 0  # Default if parsing fails

        scores[category] = {
            "score": score,
            "reasoning": "Extracted from text (JSON parsing failed)"
        }

    return scores

# ============================================================================
# DATASET EVALUATION
# ============================================================================

def evaluate_dataset(
    dataset_path: str,
    output_dir: str,
    rubric: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Evaluate entire dataset and save results.

    Args:
        dataset_path: Path to CSV with columns: query, response
        output_dir: Directory to save results
        rubric: Rubric configuration

    Returns:
        Dictionary with aggregate metrics and individual results
    """

    print(f"\n📊 EvalCraft Evaluation")
    print(f"Project: {PROJECT_NAME}")
    print(f"Dataset: {dataset_path}")
    print(f"Judge Model: {JUDGE_MODEL} (temperature={JUDGE_TEMPERATURE})")
    print(f"Categories: {', '.join(rubric.keys())}\n")

    # Load dataset
    try:
        df = pd.read_csv(dataset_path)
        required_cols = ['query', 'response']
        if not all(col in df.columns for col in required_cols):
            print(f"❌ Dataset must have columns: {required_cols}")
            print(f"Found columns: {list(df.columns)}")
            sys.exit(1)

    except Exception as e:
        print(f"❌ Error loading dataset: {e}")
        sys.exit(1)

    print(f"✅ Loaded {len(df)} test cases\n")

    # Initialize client
    client = get_anthropic_client()

    # Evaluate each case
    results = []
    print("Evaluating test cases...")

    for idx, row in df.iterrows():
        print(f"  [{idx+1}/{len(df)}] Evaluating...", end="\r")

        eval_result = evaluate_single(
            client=client,
            query=row['query'],
            response=row['response'],
            rubric=rubric
        )

        results.append({
            "test_case_id": idx,
            "query": row['query'],
            "response": row['response'],
            "scores": eval_result['scores'],
            "judge_reasoning": eval_result['judge_reasoning'],
            "success": eval_result['success']
        })

    print(f"\n✅ Evaluation complete!\n")

    # Aggregate results
    aggregate_metrics = aggregate_results(results, rubric)

    # Save results
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    run_dir = Path(output_dir) / f"run_{timestamp}"
    run_dir.mkdir(parents=True, exist_ok=True)

    save_results(results, aggregate_metrics, run_dir, rubric)

    return {
        "results": results,
        "metrics": aggregate_metrics,
        "run_dir": str(run_dir)
    }

# ============================================================================
# RESULT AGGREGATION
# ============================================================================

def aggregate_results(results: List[Dict[str, Any]], rubric: Dict[str, Any]) -> Dict[str, Any]:
    """
    Calculate aggregate metrics across all test cases.

    Best practice: Don't optimize for high pass rates - a 70% pass rate
    might indicate more meaningful evaluation than 100%.
    """

    category_scores = {cat: [] for cat in rubric.keys()}
    pass_counts = {cat: 0 for cat in rubric.keys()}
    overall_pass_count = 0

    for result in results:
        if not result['success']:
            continue

        # Collect per-category scores
        for category, details in result['scores'].items():
            if category in category_scores:
                score = details['score']
                category_scores[category].append(score)

                # Check if passes threshold
                if score >= rubric[category]['pass_threshold']:
                    pass_counts[category] += 1

        # Check overall pass
        if check_overall_pass(result['scores'], rubric):
            overall_pass_count += 1

    # Calculate statistics
    num_cases = len([r for r in results if r['success']])

    metrics = {
        "total_cases": num_cases,
        "overall_pass_count": overall_pass_count,
        "overall_pass_rate": overall_pass_count / num_cases if num_cases > 0 else 0,
        "categories": {}
    }

    for category, scores in category_scores.items():
        if len(scores) > 0:
            import statistics
            metrics["categories"][category] = {
                "mean": statistics.mean(scores),
                "median": statistics.median(scores),
                "stdev": statistics.stdev(scores) if len(scores) > 1 else 0,
                "min": min(scores),
                "max": max(scores),
                "pass_count": pass_counts[category],
                "pass_rate": pass_counts[category] / len(scores),
                "pass_threshold": rubric[category]['pass_threshold']
            }

    return metrics

def check_overall_pass(scores: Dict[str, Dict[str, Any]], rubric: Dict[str, Any]) -> bool:
    """
    Determine if this case passes overall evaluation.

    Uses logic defined in RUBRIC configuration:
    - ALL_MUST_PASS: Every category must meet its threshold
    - Weighted average: Average score must meet overall threshold
    """

    if USE_ALL_MUST_PASS:
        # All categories must pass
        for category, details in scores.items():
            if category not in rubric:
                continue
            if details['score'] < rubric[category]['pass_threshold']:
                return False
        return True
    else:
        # Weighted average must pass
        weighted_sum = 0
        total_weight = 0

        for category, details in scores.items():
            if category not in rubric:
                continue
            weight = rubric[category].get('weight', 1.0)
            weighted_sum += details['score'] * weight
            total_weight += weight

        weighted_avg = weighted_sum / total_weight if total_weight > 0 else 0
        return weighted_avg >= OVERALL_THRESHOLD

# ============================================================================
# RESULT SAVING
# ============================================================================

def save_results(
    results: List[Dict[str, Any]],
    metrics: Dict[str, Any],
    run_dir: Path,
    rubric: Dict[str, Any]
):
    """
    Save results in multiple formats:
    - scores.json: Structured results
    - flagged_failures.csv: Cases that failed evaluation
    - report.html: Interactive HTML report
    """

    # Save structured JSON
    with open(run_dir / "scores.json", "w") as f:
        json.dump({
            "project": PROJECT_NAME,
            "timestamp": datetime.now().isoformat(),
            "metrics": metrics,
            "results": results
        }, f, indent=2)

    # Save flagged failures
    failures = []
    for result in results:
        if not result['success']:
            failures.append(result)
            continue

        if not check_overall_pass(result['scores'], rubric):
            failures.append(result)

    if failures:
        failure_rows = []
        for f in failures:
            row = {
                "test_case_id": f['test_case_id'],
                "query": f['query'],
                "response": f['response']
            }
            for cat, details in f['scores'].items():
                row[f"{cat}_score"] = details['score']
            failure_rows.append(row)

        df_failures = pd.DataFrame(failure_rows)
        df_failures.to_csv(run_dir / "flagged_failures.csv", index=False)

    # Generate HTML report
    generate_html_report(results, metrics, run_dir, rubric)

    print(f"📁 Results saved to: {run_dir}/")
    print(f"   - scores.json (structured results)")
    print(f"   - flagged_failures.csv ({len(failures)} cases)")
    print(f"   - report.html (interactive report)")

# ============================================================================
# HTML REPORT GENERATION
# ============================================================================

def generate_html_report(
    results: List[Dict[str, Any]],
    metrics: Dict[str, Any],
    run_dir: Path,
    rubric: Dict[str, Any]
):
    """
    Generate interactive HTML report with embedded data.

    Report includes:
    - Summary metrics
    - Per-category scores
    - Individual test cases with scores
    - Filtering and sorting
    """

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{PROJECT_NAME} - Evaluation Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 20px; background: #f5f5f5; }}
        .container {{ max-width: 1400px; margin: 0 auto; }}
        .header {{ background: white; padding: 30px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .header h1 {{ color: #333; margin-bottom: 10px; }}
        .header .meta {{ color: #666; font-size: 14px; }}

        .metrics {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 20px; }}
        .metric-card {{ background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .metric-card h3 {{ color: #666; font-size: 14px; font-weight: 600; margin-bottom: 8px; }}
        .metric-card .value {{ font-size: 32px; font-weight: bold; color: #333; }}
        .metric-card .subtext {{ color: #999; font-size: 14px; margin-top: 4px; }}
        .pass {{ color: #10b981; }}
        .fail {{ color: #ef4444; }}

        .test-cases {{ background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        .test-case {{ border-bottom: 1px solid #eee; padding: 20px 0; }}
        .test-case:last-child {{ border-bottom: none; }}
        .test-case .case-header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; cursor: pointer; }}
        .test-case .case-id {{ font-weight: 600; color: #333; }}
        .test-case .scores {{ display: flex; gap: 15px; }}
        .test-case .score-badge {{ padding: 4px 12px; border-radius: 4px; font-size: 14px; font-weight: 600; }}
        .test-case .score-badge.pass {{ background: #d1fae5; color: #065f46; }}
        .test-case .score-badge.fail {{ background: #fee2e2; color: #991b1b; }}

        .test-case .details {{ display: none; margin-top: 15px; }}
        .test-case.expanded .details {{ display: block; }}
        .test-case .query {{ background: #f9fafb; padding: 15px; border-radius: 4px; margin-bottom: 10px; }}
        .test-case .response {{ background: #f9fafb; padding: 15px; border-radius: 4px; margin-bottom: 10px; }}
        .test-case .score-detail {{ background: #f9fafb; padding: 15px; border-radius: 4px; margin-bottom: 10px; }}
        .test-case .score-detail h4 {{ color: #333; margin-bottom: 8px; }}
        .test-case .score-detail .score {{ font-size: 20px; font-weight: bold; }}
        .test-case .score-detail .reasoning {{ color: #666; font-size: 14px; margin-top: 8px; }}

        .filters {{ margin-bottom: 20px; display: flex; gap: 10px; flex-wrap: wrap; }}
        .filters button {{ padding: 8px 16px; border: 1px solid #ddd; background: white; border-radius: 4px; cursor: pointer; }}
        .filters button.active {{ background: #3b82f6; color: white; border-color: #3b82f6; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{PROJECT_NAME} - Evaluation Report</h1>
            <div class="meta">
                Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")} |
                Test Cases: {metrics['total_cases']} |
                Judge Model: {JUDGE_MODEL}
            </div>
        </div>

        <div class="metrics">
            <div class="metric-card">
                <h3>Overall Pass Rate</h3>
                <div class="value {'pass' if metrics['overall_pass_rate'] >= 0.7 else 'fail'}">
                    {metrics['overall_pass_rate']:.1%}
                </div>
                <div class="subtext">{metrics['overall_pass_count']}/{metrics['total_cases']} cases passed</div>
            </div>
"""

    # Add per-category metrics
    for category, cat_metrics in metrics['categories'].items():
        status_class = 'pass' if cat_metrics['pass_rate'] >= 0.7 else 'fail'
        html += f"""
            <div class="metric-card">
                <h3>{category.title()}</h3>
                <div class="value {status_class}">{cat_metrics['mean']:.1f}/5.0</div>
                <div class="subtext">
                    Pass rate: {cat_metrics['pass_rate']:.1%} (≥{cat_metrics['pass_threshold']})
                </div>
            </div>
"""

    html += """
        </div>

        <div class="test-cases">
            <h2 style="margin-bottom: 20px;">Test Cases</h2>

            <div class="filters">
                <button class="active" onclick="filterCases('all')">All Cases</button>
                <button onclick="filterCases('pass')">Passed</button>
                <button onclick="filterCases('fail')">Failed</button>
            </div>

            <div id="test-case-list">
"""

    # Add individual test cases
    for result in results:
        if not result['success']:
            continue

        overall_pass = check_overall_pass(result['scores'], rubric)
        pass_class = 'pass' if overall_pass else 'fail'
        pass_text = 'PASS' if overall_pass else 'FAIL'

        html += f"""
            <div class="test-case" data-pass="{str(overall_pass).lower()}">
                <div class="case-header" onclick="this.parentElement.classList.toggle('expanded')">
                    <div class="case-id">Test Case #{result['test_case_id']}</div>
                    <div class="scores">
                        <span class="score-badge {pass_class}">{pass_text}</span>
"""

        # Add per-category badges
        for category, details in result['scores'].items():
            if category not in rubric:
                continue
            threshold = rubric[category]['pass_threshold']
            score = details['score']
            badge_class = 'pass' if score >= threshold else 'fail'
            html += f'<span class="score-badge {badge_class}">{category.title()}: {score}/5</span>'

        html += """
                    </div>
                </div>
                <div class="details">
"""

        # Add query and response
        html += f"""
                    <div class="query">
                        <strong>Query:</strong><br>
                        {result['query']}
                    </div>
                    <div class="response">
                        <strong>Response:</strong><br>
                        {result['response']}
                    </div>
"""

        # Add score details
        for category, details in result['scores'].items():
            if category not in rubric:
                continue
            threshold = rubric[category]['pass_threshold']
            score = details['score']
            score_class = 'pass' if score >= threshold else 'fail'

            html += f"""
                    <div class="score-detail">
                        <h4>{category.title()}</h4>
                        <div class="score {score_class}">{score}/5.0 (threshold: ≥{threshold})</div>
                        <div class="reasoning">{details.get('reasoning', 'No reasoning provided')}</div>
                    </div>
"""

        html += """
                </div>
            </div>
"""

    html += """
            </div>
        </div>
    </div>

    <script>
        function filterCases(filter) {
            const cases = document.querySelectorAll('.test-case');
            const buttons = document.querySelectorAll('.filters button');

            buttons.forEach(btn => btn.classList.remove('active'));
            event.target.classList.add('active');

            cases.forEach(c => {
                if (filter === 'all') {
                    c.style.display = 'block';
                } else if (filter === 'pass') {
                    c.style.display = c.dataset.pass === 'true' ? 'block' : 'none';
                } else if (filter === 'fail') {
                    c.style.display = c.dataset.pass === 'false' ? 'block' : 'none';
                }
            });
        }
    </script>
</body>
</html>
"""

    # Save HTML report
    report_path = run_dir / "report.html"
    with open(report_path, "w") as f:
        f.write(html)

    print(f"\n📊 Opening interactive report in browser...")
    webbrowser.open(f"file://{report_path.absolute()}")

# ============================================================================
# COMMAND-LINE INTERFACE
# ============================================================================

def print_summary(metrics: Dict[str, Any]):
    """Print evaluation summary to console."""

    print("\n" + "="*60)
    print("EVALUATION SUMMARY")
    print("="*60)

    print(f"\n📊 Overall Results:")
    print(f"   Pass Rate: {metrics['overall_pass_rate']:.1%} ({metrics['overall_pass_count']}/{metrics['total_cases']} cases)")

    pass_emoji = "✅" if metrics['overall_pass_rate'] >= 0.7 else "⚠️"
    print(f"   Status: {pass_emoji}")

    print(f"\n📈 Per-Category Scores:")
    for category, cat_metrics in metrics['categories'].items():
        status = "✅" if cat_metrics['pass_rate'] >= 0.7 else "⚠️"
        print(f"   {status} {category.title()}: {cat_metrics['mean']:.1f}/5.0 (pass rate: {cat_metrics['pass_rate']:.1%})")

    print(f"\n💡 Recommendations:")
    if metrics['overall_pass_rate'] >= 0.9:
        print(f"   • Pass rate is very high ({metrics['overall_pass_rate']:.1%}) - consider if evals are challenging enough")
    elif metrics['overall_pass_rate'] < 0.5:
        print(f"   • Pass rate is low ({metrics['overall_pass_rate']:.1%}) - review flagged_failures.csv for patterns")

    lowest_cat = min(metrics['categories'].items(), key=lambda x: x[1]['mean'])
    print(f"   • Focus on improving: {lowest_cat[0].title()} (lowest score: {lowest_cat[1]['mean']:.1f}/5.0)")

    print(f"\n" + "="*60 + "\n")

def main():
    """Main entry point for evaluation script."""

    parser = argparse.ArgumentParser(
        description="Evaluate AI agent outputs using LLM-as-judge",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python evaluate.py --input test_dataset.csv
    python evaluate.py --input test_dataset.csv --output-dir custom_results/

The dataset CSV must have columns: query, response
Optionally: label (for validation against human scores)
        """
    )

    parser.add_argument(
        "--input",
        required=True,
        help="Path to input CSV dataset (columns: query, response)"
    )

    parser.add_argument(
        "--output-dir",
        default="results",
        help="Directory to save results (default: results/)"
    )

    args = parser.parse_args()

    # Validate input file
    if not Path(args.input).exists():
        print(f"❌ Input file not found: {args.input}")
        sys.exit(1)

    # Run evaluation
    evaluation = evaluate_dataset(
        dataset_path=args.input,
        output_dir=args.output_dir,
        rubric=RUBRIC
    )

    # Print summary
    print_summary(evaluation['metrics'])

    print(f"✅ Evaluation complete! Results saved to: {evaluation['run_dir']}/")
    print(f"   View the interactive HTML report for detailed analysis.")

if __name__ == "__main__":
    main()
